name: Publish UnityPackage

on:
  push:
    tags: # v1.0, v1.1, etc..
      - v*

jobs:
  generate-pacakge:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1.1.0
        with:
          path: UnityProject/Library
          key: Library
      - name: Generate package
        uses: webbertakken/unity-builder@v1.4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: UnityProject
          unityVersion: 2020.3.4f1
          targetPlatform: StandaloneLinux64
          buildsPath: Build
          versioning: None
          buildMethod: Cathei.BakingSheet.Editor.PackageGenerationTools.GeneratePackage
      - name: Upload Unity package
        uses: actions/upload-artifact@v2
        with:
          name: Unity Package
          path: Build/*.unitypackage
