name: Publish UnityPackage

on:
  push:
    tags: # v1.0, v1.1, etc..
      - v*
  workflow_dispatch:

jobs:
  generate-pacakge:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v1.1.0
        with:
          path: UnityProject/Library
          key: Library
      - name: Generate package
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: UnityProject
          unityVersion: auto
          targetPlatform: StandaloneLinux64
          buildsPath: Build
          versioning: None
          buildMethod: Cathei.BakingSheet.Editor.PackageGenerationTools.GeneratePackage
      - name: Upload Unity package
        uses: actions/upload-artifact@v2
        with:
          name: Unity Package
          path: Build/*.unitypackage
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: Build/*.unitypackage
